const mongoose=require("mongoose")
const adressSchema=new mongoose.Schema({
user:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"data",
    required:true
},
address:[{
    Name:{
        type:String,
        required:true,
    },
    Locality:{
        type:String,
        required:true,
    },
    Phone:{
        type:Number,
        required:true,
    },
    District:{
        type:String,
        required:true,
    },
    State:{
        type:String,
        required:true,
    },
    City:{
        type:String,
        required:true,
    },
    HouseName:{
        type:String,
        required:true,
    },
    Pincode:{
        type:Number,
        required:true,
    },
}]
})
module.exports=mongoose.model("adress",adressSchema)